services:
  db:
    image: mysql:8.0
    container_name: evcs-mysql
    environment:
      MYSQL_DATABASE: evcs
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  ports:
    - "${MYSQL_PORT}:3306"
  volumes:
    - db_data:/var/lib/mysql
  command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]


app:
  build: .
  container_name: evcs-app
  depends_on:
    - db
  environment:
  DB_USERNAME: ${DB_USERNAME}
  DB_PASSWORD: ${DB_PASSWORD}
  SERVER_PORT: ${SERVER_PORT}
  # point Spring to the DB container
  SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/evcs?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
  ports:
    - "${SERVER_PORT}:8080"
  command: ["java","-jar","/app/app.jar"]

volumes:
  db_data: